"""
Django settings for extract_web project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import yaml
import dashscope

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- BEGIN ADDED: Load DashScope API Key from config.yaml ---
CONFIG_YAML_PATH = BASE_DIR / "config.yaml"
try:
    with open(CONFIG_YAML_PATH, "r") as f:
        config_data = yaml.safe_load(f)
        DASHSCOPE_API_KEY = config_data.get("DASHSCOPE_API_KEY")
        if DASHSCOPE_API_KEY:
            dashscope.api_key = DASHSCOPE_API_KEY
            print(
                f"Successfully loaded DASHSCOPE_API_KEY from {CONFIG_YAML_PATH}"
            )  # For verification
        else:
            print(f"DASHSCOPE_API_KEY not found in {CONFIG_YAML_PATH}")
except FileNotFoundError:
    print(f"Warning: {CONFIG_YAML_PATH} not found. DASHSCOPE_API_KEY not loaded.")
except Exception as e:
    print(f"Warning: Error loading DASHSCOPE_API_KEY from {CONFIG_YAML_PATH}: {e}")
# --- END ADDED ---


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-5%w97o8ra8mr6iolgcz790_ky0jg8)k@hb-xft+f-4pe+dbnxc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "converter",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-Hans"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "converter/static/converter"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Media files (user-uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "his_pic"

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # 保留 Django 已有的 logger
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {  # 保留控制台输出，方便开发时查看
            "level": "DEBUG",  # 开发时控制台可以输出 DEBUG 级别
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "DEBUG",  # 文件中记录 INFO 级别及以上
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "django.log",  # 日志文件路径
            "maxBytes": 1024 * 1024 * 5,  # 5 MB 文件大小上限
            "backupCount": 2,  # 保留2个备份文件
            "formatter": "verbose",
        },
        "app_file": {  # 新增 app.log handler
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "app.log",
            "maxBytes": 1024 * 1024 * 5,
            "backupCount": 2,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {  # Django 框架本身的 logger
            "handlers": ["console", "file"],
            "level": "INFO",  # Django 框架的日志级别
            "propagate": True,
        },
        "converter": {  # 我们 converter 应用的 logger
            "handlers": ["console", "file"],
            "level": "DEBUG",  # 应用日志级别可以更详细
            "propagate": False,  # 不向上传播给 root logger，避免重复记录
        },
        "ocr_system": {  # 新增 ocr_system logger
            "handlers": ["console", "app_file"],  # 只写 app.log
            "level": "DEBUG",
            "propagate": False,
        },
        # 可以为其他应用配置 logger
    },
    "root": {  # 根 logger，捕获所有未被特定 logger 处理的日志
        "handlers": ["console", "file"],
        "level": "INFO",  # 根 logger 默认级别
    },
}
